CREATE TABLE "TRAINING"."ACCOUNT" 
   (	"ID" VARCHAR2(18), 
	"ISPERSONACCOUNT" VARCHAR2(5), 
	"LASTNAME" VARCHAR2(255), 
	"FIRSTNAME" VARCHAR2(255), 
	"PERSONEMAIL" VARCHAR2(255), 
	"PERSONMOBILEPHONE" VARCHAR2(255), 
	"DYNAMICS_ID__C" VARCHAR2(255), 
	"PERSONBIRTHDATE" DATE, 
	"BILLINGSTREET" VARCHAR2(255), 
	"BILLINGCITY" VARCHAR2(255), 
	"BILLINGSTATE" VARCHAR2(255), 
	"BILLINGPOSTALCODE" VARCHAR2(255), 
	"BILLINGADDRESSOTHER__C" VARCHAR2(255), 
	 CONSTRAINT "ACCOUNT_ID_PK" PRIMARY KEY ("ID")
  USING INDEX);